name: "CI"
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@v14
      - name: build
        run: |
          emcc -O3 --no-entry -s WASM=1 -s ENVIRONMENT=web -s ERROR_ON_UNDEFINED_SYMBOLS=0 script.c -o script.wasm
      - name: export
        run: |
          curl -F "data=@./script.wasm" "https://www.d1ag0n.com/api/Wasm/Upload/${{secrets.API_UPLOAD_KEY}}"
