name: "CI"
on:
  workflow_dispatch:
  push:
    #branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ln
        run: ln -s /usr/bin/wasm-ld-12 wasm-ld
      - name: build
        run: |
          clang --target=wasm32 -O3 -flto -nostdlib -Wl,--no-entry -Wl,--export-all -Wl,--lto-O3 -o script.wasm script.c
      - name: export
        run: |
          curl -F "data=@./script.wasm" "https://www.d1ag0n.com/api/Wasm/Upload/${{secrets.WASMMODULE_TOKEN}}"
