name: "emsdk"
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mymindstorm/setup-emsdk@v11
      - name: build
        run: emcc script.c -o script.wasm
      - name: export
        run: |
          curl -H "X-WASMModule-Token: ${{secrets.WASMMODULE_TOKEN}}" -F "data=@.\script.wasm" "https://wws.d1ag0n.com/api/wasm-module/upload"
